sylius_grid:
    grids:
        app_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.supplier.class%"
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: 'Name'
                    sortable: ~
                email:
                    type: string
                    label: app.ui.email
                    sortable: ~
                state:
                    type: twig
                    label: 'State'
                    options:
                        template: 'state.html.twig'
            filters:
                name:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    verify:
                        type: apply_transition
                        label: 'Verify'
                        icon: checkmark
                        options:
                            class: green
                            link:
                                route: app_admin_supplier_verify
                                parameters:
                                    id: resource.id
                            transition: verify
                            graph: app_supplier
                    update:
                        type: update
                    delete:
                        type: delete

        sylius_admin_product_variant:
            fields:
                supplier:
                    type: twig
                    label: 'Supplier'
                    options:
                        template: Grid/Field/supplier.html.twig
            filters:
                supplier:
                    type: entity
                    label: 'Supplier'
                    form_options:
                        choice_label: name
                        class: "%app.model.supplier.class%"
                        required: false
                name:
                    form_options:
                        type: contains
