sylius_grid:
    grids:
        app_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.supplier.class%"
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: 'Name'
                    sortable: ~
                email:
                    type: string
                    label: app.ui.email
                    sortable: ~
            filters:
                name:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
