winzou_state_machine:
    app_supplier:
        class: "%app.model.supplier.class%"
        property_path: state
        graph: app_supplier
        state_machine_class: "%sylius.state_machine.class%"
        states:
            unverified: ~
            verified: ~
        transitions:
            verify:
                from: [unverified]
                to: verified
        callbacks:
            after:
                app_supplier_verified:
                    on: ['verify']
                    do: ['@App\VerifiedSupplierNotifierInterface', 'notify']
                    args: ['object']
                    
    sylius_shipment:
        callbacks:
            before:
                app_assign_tracking_code_to_shipment:
                    on: ['ship']
                    do: ['@App\Listener\AssignTrackingCodeToShipmentListener', '__invoke']
                    args: ['object']
