app_admin_supplier:
    resource: |
        alias: app.supplier
        section: admin
        except: ['show']
        templates: SyliusAdminBundle:Crud
        grid: app_supplier
        vars:
            all:
                icon: dolly
    type: sylius.resource
    prefix: admin

app_admin_supplier_verify:
    path: /admin/suppliers/{id}/verify
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: verify
            redirect: referer
            flash: app.supplier_verified

